import "./globals.css";
import Navbar from "./components/Navbar";
import MyProflePic from "./components/MyProflePic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <Navbar />
        <MyProflePic />
        {children}
      </body>
    </html>
  );
}
